FROM golang:1.24.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
COPY ./service2/ ./service2/

RUN go mod download
RUN go build -o service2/build/app service2/cmd/app/main.go

FROM alpine:3.18

RUN mkdir -p /service2

COPY --from=builder ./app/service2/build/app /service2
COPY --from=builder ./app/service2/docker-config.yaml /service2

CMD ["/service2/app"]
