FROM golang:1.24.3-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
COPY ./in_memory/ ./in_memory/
COPY ./service1/ ./service1/

RUN go mod download
RUN go build -o service1/build/app service1/cmd/app/main.go

FROM alpine:3.18

RUN mkdir -p /service1

COPY --from=builder ./app/service1/build/app /service1
COPY --from=builder ./app/service1/docker-config.yaml /service1

EXPOSE 8081

CMD ["/service1/app"]
