server:
  read_timeout: 20s
  write_timeout: 20s
  shutdown_timeout: 20s
router:
  create:
    fail_timeout: 10s
  list:
  list_id:
kafka:
  batch_timeout: 50ms
  required_acks: -1
  allow_topic_creation: true